- src/main/web_src/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- src/main/web_src/src/components/bestillingsveileder/bestillingTypes.ts
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg3/BestillingInfoboks.tsx
- src/main/web_src/src/components/fagsystem/tpsf/form/personinformasjon/Personinformasjon.js
- src/main/web_src/src/components/fagsystem/tpsf/form/personinformasjon/partials/Diverse.js
- src/main/web_src/src/components/fagsystem/tpsf/form/validation.js
- src/main/web_src/src/components/fagsystem/tpsf/visning/partials/Personinfo.js
- src/main/web_src/src/components/ui/form/formUtils.js
Skjerming settes ved dato f.o.m i bestilling, for å avslutte skjerming setter man dato.t.o.m i legg til på person.
> Reg 8911 dolly frontend skjerming av egenansatte

- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Udi.js
- src/main/web_src/src/components/miljoVelger/MiljoeInfo/MiljoeInfo.js
Har lagt på info i UDI-stub panel, og miljøinfo i siste steg for de som ikke har sjekket/husker infoboksen. Forståelig? Too much?
> Lagt til infoboks i steg 1 og 3

- src/main/web_src/src/pages/gruppe/PersonListe/PersonListe.js
- src/main/web_src/src/pages/gruppe/PersonVisning/PersonVisning.less
Ble nødt til å fikse det her etter å ha testa en del i Dolly de siste to dagene.
> Legge til luft mellom identnr og kopiknapp i personvisning

- src/main/web_src/src/pages/tpsEndring/SendDoedsmelding.js
- src/main/web_src/src/pages/tpsEndring/SendFoedselsmelding.js
- src/main/web_src/src/pages/tpsEndring/TpsEndring.js
- src/main/web_src/src/pages/tpsEndring/TpsEndring.less
Bare å komme med kommetar på designet mitt :)
Se hvordan det blir logget i 
https://logs.adeo.no/app/kibana#/dashboard/cc111420-6ace-11ea-a213-6f2e5628fd30?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Dolly%20-%20Frontend',viewMode:view)
> Logg endringsmeldinger og infomer om fjerning av meldingene

- src/main/web_src/src/pages/tpsEndring/TpsEndring.js
Kommentar på ordlyd? Pirk er som alltid lov!
> Lagt til et alternativ til under fødselsmelding

- src/main/web_src/src/components/bestillingsveileder/bestillingTypes.ts
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/Steg1.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg2/Steg2.js
- src/main/web_src/src/pages/gruppe/BestillingListe/BestillingListe.js
- src/main/web_src/src/pages/gruppe/PersonListe/PersonListe.js
- src/main/web_src/src/pages/gruppe/PersonListe/PersonListeConnector.js
- src/main/web_src/src/pages/gruppe/PersonVisning/TidligereBestillinger/TidligereBestillinger.js
Bitteliten PR. 
Endret tekst i steg 2 dersom "Legg til" og ikke huket av noe i steg 1. Fjernet også noen importer som Sonar klager på.
> Endret tekst i steg2 ved legg til

- src/main/web_src/src/components/bestilling/detaljer/Detaljer.js
- src/main/web_src/src/pages/minSide/maler/EndreMalnavn.js
- src/main/web_src/src/pages/minSide/maler/MalModal.js
Mulighet til å lage mal av sendte bestillinger i bestillinger tab på en gruppe
> Lage mal etter en bestilling

- src/main/web_src/src/components/fagsystem/inntektsmelding/form/Form.tsx
- src/main/web_src/src/components/ui/form/inputWarning/inputWarning.less
- src/main/web_src/src/components/ui/form/inputWarning/inputWarning.tsx
Tenker at denne komponenten også kan brukes på andre felter som egentlig skal fylles ut, men som vi ønsker å holde åpne for negativ testing. Kom ikke på noen i farta, men kan legges inn etterhvert som behov dukker opp.
Ellers har jeg brukt flaut lang tid på å få til stylingen slik jeg ønsket, og føler nå at jeg har sett meg helt blind på ting. Blir derfor ekstra glad for innspill 😉
> Varsel om automatisk behandling av IM

- src/main/web_src/src/components/fagsystem/inntektsmelding/form/Form.tsx
- src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/InntektsmeldingYtelseSelect.tsx
- src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/sykepengerForm.tsx
- src/main/web_src/src/components/fagsystem/inntektsmelding/visning/Visning.tsx
- src/main/web_src/src/components/fagsystem/inntektsmelding/visning/partials/enkelInntektsmeldingVisning.tsx
Kom inn et ønske om dette på dolly-og-sif kanal, blir ikke noen problemer av å ha med den der også? 😅
> Lagt til mulighet for sykepengerIArbeidsgiverperioden på omsorgspenger

- src/main/web_src/src/components/enhetstre/Enhetstre.less
- src/main/web_src/src/components/enhetstre/Enhetstre.tsx
- src/main/web_src/src/components/enhetstre/Node.tsx
- src/main/web_src/src/components/enhetstre/index.ts
- src/main/web_src/src/components/enhetstre/types.ts
Har lagd en komponent for enhetstre hvor det også er mulig å endre på hvilken som er valgt.
For å teste treet og endring av valgt enhet (se bilde over) brukte jeg følgende kodesnutter:
```
const test = [
{
name: 'Super Bedrift',
id: 1,
underenheter: [
{
name: 'Lynvingen Logistikk',
id: 2,
underenheter: [
{
name: 'Mirakelkvinnen Markedsføring',
id: 5
}
]
},
{
name: 'Supermann Sjåførservice',
id: 3,
underenheter: [
{
name: 'Grønne Lykts Lamper og Lys',
id: 4,
underenheter: [
{
name: 'Aquaman Kildevann',
id: 6,
underenheter: [
{
name: 'Lynet Lydtekniker',
id: 7
}
]
}
]
}
]
}
]
}
]
const [selectedOrg, setSelectedOrg] = useState(1)
const onNodeClick = (enhet: Enhet) => {
setSelectedOrg(enhet.id)
}
<Enhetstre enheter={test} selectedEnhet={selectedOrg} onNodeClick={onNodeClick} />
```
> Organisasjonsoversikt

- src/main/web_src/src/components/bestilling/statusListe/BestillingProgresjon/BestillingProgresjon.js
- src/main/web_src/src/ducks/bestilling/index.js
- src/main/web_src/src/service/services/dolly/DollyService.js
Tar i bruk endepunktet som henter status på bestillingId, må endres til å tas i bruk etter navigasjon til organisasjon på en måte, usikker på om dette er noe Betsy allerede holder på med og at bare endepunktet manglet😄
> Organisasjon endringer

- src/main/web_src/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/StegVelger.js
- src/main/web_src/src/components/fagsystem/inntektstub/form/partials/inntektsinformasjonForm.tsx
og fikset måned/år label til å heller vise år/måned som er formatet som er brukt
> Endret måned input for inntektskomponenten til å fungere i alle nettlesere

- src/main/web_src/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/StegVelger.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/OrganisasjonDetaljer.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/form/Form.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/form/partials/Detaljer.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/form/paths.ts
- src/main/web_src/src/components/fagsystem/organisasjoner/types.ts
- src/main/web_src/src/components/fagsystem/organisasjoner/visning/Detaljer.tsx
- src/main/web_src/src/components/ui/form/formUtils.js
- src/main/web_src/src/config/kodeverk/index.ts
- src/main/web_src/src/pages/organisasjoner/OrganisasjonListe.tsx
- src/main/web_src/src/pages/organisasjoner/Organisasjoner.tsx
- src/main/web_src/src/service/SelectOptions.tsx
- src/main/web_src/src/service/services/dolly/Utils.js
Fra nå av prøver jeg meg på søte, små PRer 😉  Har lagt til sektorkode, stiftelsesdato og målform i bestilling og visning.
> Org nye attributter

- config.dev.yml
- src/main/java/no/nav/dolly/web/config/ApplicationConfig.java
- src/main/web_src/src/components/fagsystem/organisasjoner/form/Form.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/form/partials/Detaljer.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/visning/Detaljer.tsx
- src/main/web_src/src/components/fagsystem/organisasjoner/visning/Visning.tsx
- src/main/web_src/src/components/ui/form/fieldArray/dollyFieldArray.less
- src/main/web_src/src/components/ui/form/kategori/kategori.less
- src/main/web_src/src/config/kodeverk/index.ts
- src/main/web_src/src/ducks/bestilling/index.js
- src/main/web_src/src/service/services/dolly/DollyEndpoints.js
- src/main/web_src/src/service/services/dolly/DollyService.js
Forsøkt å fikse en del av de problemene på Trello boardet
> Org bestilling fix temp endringer

- src/main/web_src/src/components/fagsystem/pdlf/visning/partials/PdlNasjonalitet.js
- src/main/web_src/src/components/fagsystem/pdlf/visning/partials/PdlPersonInfo.js
Feil meldt inn på dolly kanal i sammenheng med delay av oppretting hos PDL
> PDL visning fiks dersom ident bare delvis er opprettet

- src/main/web_src/src/ducks/organisasjon/index.js
Viser warning-symbol på organisasjoner hvor bestillingen ikke er "ok".
> Tilpasset statussymboler på organisasjoner

- src/main/web_src/src/components/bestilling/sammendrag/kriterier/OrganisasjonKriterier.tsx
- src/main/web_src/src/components/enhetstre/Enhetstre.tsx
- src/main/web_src/src/components/enhetstre/Node.tsx
- src/main/web_src/src/components/enhetstre/OrgTree.tsx
- src/main/web_src/src/components/enhetstre/index.ts
- src/main/web_src/src/components/enhetstre/types.ts
- src/main/web_src/src/components/fagsystem/organisasjoner/visning/Visning.tsx
Jeg synes denne var veldig vanskelig å forklare i tekst men lagde en review PR.
> Simplifiser visning av enhetstre

- src/main/web_src/src/components/bestilling/detaljer/Detaljer.js
- src/main/web_src/src/components/bestilling/sammendrag/Sammendrag.js
- src/main/web_src/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- src/main/web_src/src/components/bestilling/statusListe/BestillingProgresjon/BestillingProgresjon.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/StegVelger.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg3/Steg3.js
- src/main/web_src/src/components/fagsystem/organisasjoner/form/partials/Detaljer.tsx
- src/main/web_src/src/components/miljoVelger/MiljoVelger.js
- src/main/web_src/src/utils/DataFormatter.js
Oppdaget bl.a. at flere felter i form ble nullstilt ved navigering frem og tilbake etter endringene i Detaljer.tsx. Fant ikke umiddelbart en god løsning, så jeg har endret den tilbake slik den var, for den fungerer som den skal. Men tar gjerne imot innspill på om den kan skrives bedre 😊
> Div org fix

- src/main/web_src/src/ducks/organisasjon/index.js
- src/main/web_src/src/pages/organisasjoner/Organisasjoner.tsx
Har fått testet en del med/uten tilknyttede organisasjoner - Fikk rettet et par mindre issues, men det meste ser ut til å fungere som det skal 😄
> Opprett standard organisasjon popup issue

- .github/workflows/deploy.dev.yml
- src/main/java/no/nav/dolly/web/security/OnBehalfOfGenerateAccessTokenService.java
Trenger mer info om hva som går galt
> Logging of deploy

- src/main/web_src/src/components/ui/dollyTable/DollyTable.js
- src/main/web_src/src/components/ui/dollyTable/pagination/Pagination.js
- src/main/web_src/src/ducks/finnPerson/index.js
- src/main/web_src/src/ducks/gruppe/index.js
- src/main/web_src/src/pages/gruppe/Gruppe.js
- src/main/web_src/src/pages/gruppe/GruppeConnector.js
- src/main/web_src/src/pages/gruppeOversikt/FinnPerson.less
- src/main/web_src/src/pages/gruppeOversikt/FinnPerson.tsx
- src/main/web_src/src/pages/gruppeOversikt/GruppeOversikt.js
- src/main/web_src/src/pages/gruppeOversikt/GruppeOversiktConnector.js
- src/main/web_src/src/pages/gruppeOversikt/Liste.js
- src/main/web_src/src/service/services/dolly/DollyEndpoints.js
- src/main/web_src/src/service/services/dolly/DollyService.js
Paginering på Alle grupper og en del fikser som trenges i sammenheng med det. Skal støtte både paginerte og vanlige lister nå. Finn Testperson er også blitt flyttet inn i standard søkefelt og kan nå utføres fra en annen gruppe.
> Hent alle paginering

- src/main/web_src/src/components/fagsystem/tpsf/form/familierelasjoner/partials/partnere/sivilstand/Sivilstand.js
- src/main/web_src/src/components/fagsystem/tpsf/form/validation.js
Problemet i valideringen kom av at formikbag values ikke hadde noen datoer på den forrige partneren 😅  
Endret slik at den siste gyldige datoen hentes når man oppretter ny relasjon
> Endringer i dato validering av ny partner relasjon

- src/main/web_src/src/components/fagsystem/inntektsmelding/InntektsmeldingTypes.ts
- src/main/web_src/src/components/fagsystem/inntektsmelding/form/Form.tsx
- src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/InntektsmeldingYtelseSelect.tsx
Endringer for å kunne sende inntektsmelding med barn og nærstående. 
Usikker på om Nær relasjon skal settes til true og fjernes fra valg dersom disse er valgt?
> Lagt til mulighet for Pleiepenger barn og naerstaaende

- src/main/web_src/src/components/fagsystem/tpsf/form/familierelasjoner/partials/partnere/sivilstand/SivilstandOptions.js
- src/main/web_src/src/components/fagsystem/tpsf/form/validation.js
Og satt validering på at dato skal være før dagens dato
> Gjort det mulig å tilegne ny samboer til ident

- src/main/web_src/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/StegVelger.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/KontaktReservasjon.js
- src/main/web_src/src/components/fagsystem/krrstub/form/Form.js
- src/main/web_src/src/components/fagsystem/krrstub/form/Form.tsx
- src/main/web_src/src/components/fagsystem/krrstub/visning/KrrVisning.tsx
- src/main/web_src/src/components/ui/historikk/Historikk.js
- src/main/web_src/src/ducks/gruppe/index.js
Foreslåtte endringer for å gjøre KRR mer forståelig for brukerne.
> Krr-endringer

- src/main/web_src/src/components/bestillingsveileder/stegVelger/StegVelger.js
- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg3/Steg3.js
* DisplayFormikState blir enablet automatisk dersom man er på localhost
> * Fjernet mulighet til å endre identtype ved legg til/endre på ident

- src/main/web_src/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.js
- src/main/web_src/src/components/fagsystem/tpsf/form/personinformasjon/Personinformasjon.js
- src/main/web_src/src/components/fagsystem/tpsf/form/personinformasjon/partials/Diverse.js
- src/main/web_src/src/components/fagsystem/tpsf/form/validation.js
- src/main/web_src/src/components/ui/form/formUtils.js
Kan også spesifisere ny alder, siden dette vil kunne endres når identtypen forandres
> Mulighet for endring av identtype i legg til/endre

- src/main/java/no/nav/dolly/web/config/ApplicationConfig.java
- src/main/resources/application.yml
- src/main/web_src/src/components/fagsystem/aareg/form/partials/orgnummerToggle.js
- src/main/web_src/src/components/fagsystem/inntektstub/form/partials/inntektstubOrgnummerSelect.js
- src/main/web_src/src/service/Api.js
- src/main/web_src/src/service/services/organisasjonservice/OrganisasjonService.tsx
* Koblet til Organisasjon-Service for direkte henting av org info
* Gir feedback basert på om Orgnr finnes i Q1
> Lagt til mulighet for å skrive inn orgnummer manuelt i inntektsmelding

- src/main/web_src/src/components/fagsystem/pdlf/visning/partials/PdlPersonInfo.js
Noen små endringer på PDL visning, ser ganske rart ut på adressebeskyttelse nå som det stod i oppgaven, f.eks på person med ident `08118821247`
> Formateringsendringer

- src/main/web_src/src/components/fagsystem/arena/form/Form.js
Har satt at tildato er valgfritt for dagpenger vedtak.
> Oppdatert dagpenger tildato validering

- src/main/web_src/src/components/fagsystem/aareg/form/partials/arbeidsforholdForm.js
- src/main/web_src/src/components/fagsystem/aareg/form/partials/arbeidsgiverIdent.tsx
- src/main/web_src/src/components/ui/form/inputs/textInput/TextInput.tsx
Har lagt til validering av privat arbeidsgiver ident i aareg/arbeidsforhold. Sjekker om ident finnes i noe miljø via TPS-forvalteren.
> Lagt til validering av arbeidsgiver ident
